### ISSUE TITLE
Friday-Morning-Meeting-Code-Review

### ISSUE THREAD

**Issue by johnkioko** [kaizipaul/portfolio-project#9]
Good job @kaizipaul. You have used the html 5 semantic tags, you also made sure that you do not have extra spaces in your code base.

**Comment by Allenkeys** [comment]
Great job here! :clinking_glasses:  
I think, it would be nice to reduce the numbers of selector chaining to avoid running into specificity issues later on.  :grin:

**Comment by til2to** [comment]
### Good job @kaizipaul. You have used the html 5 semantic tags, you also made sure that you do not have extra spaces in your code base.

- Kindly practice mobile first when writing code for a website to avoid multiple queries
- Also try to break your paragraph content when they become too many to make the code easy to read.

**Comment by kaizipaul** [comment]
Thank you for the feedback
